version: '3'

services:
  zen-frontend:
    build: frontend/
    command: -fallback "/index.html"
    container_name: zen-frontend
    networks:
      global:
  zen-backend:
    build: backend/
    container_name: zen-backend
    networks:
      zen-server:
      global:
  zen-database:
    image: mongo
    container_name: zen-database
    restart: always
    volumes:
      - ./data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: lenoxy
      MONGO_INITDB_ROOT_PASSWORD: hallovelo
    networks:
      zen-server:

networks:
  zen-server:
  global:
    external: true
